In [1]:
import pandas as pd

movies = pd.read_csv('data\movies.csv')
movies

<>:3: SyntaxWarning: invalid escape sequence '\m'
<>:3: SyntaxWarning: invalid escape sequence '\m'
C:\Users\jeeva\AppData\Local\Temp\ipykernel_20332\3292824437.py:3: SyntaxWarning: invalid escape sequence '\m'
  movies = pd.read_csv('data\movies.csv')

,Unnamed: 0,id,title,vote_average,vote_count,runtime,original_language,overview,popularity,genres,combined_text
0,0,27205,Inception,8.364,34495,148,en,"Cobb, a skilled thief who commits corporate es...",83.952,"Action, Science Fiction, Adventure","MOVIE_ID: 27205, Title: Inception, Overview: C..."
1,1,157336,Interstellar,8.417,32571,169,en,The adventures of a group of explorers who mak...,140.241,"Adventure, Drama, Science Fiction","MOVIE_ID: 157336, Title: Interstellar, Overvie..."
2,2,155,The Dark Knight,8.512,30619,152,en,Batman raises the stakes in his war on crime. ...,130.643,"Drama, Action, Crime, Thriller","MOVIE_ID: 155, Title: The Dark Knight, Overvie..."
3,3,19995,Avatar,7.573,29815,162,en,"In the 22nd century, a paraplegic Marine is di...",79.932,"Action, Adventure, Fantasy, Science Fiction","MOVIE_ID: 19995, Title: Avatar, Overview: In t..."
4,4,24428,The Avengers,7.710,29166,143,en,When an unexpected enemy emerges and threatens...,98.082,"Science Fiction, Action, Adventure","MOVIE_ID: 24428, Title: The Avengers, Overview..."
...,...,...,...,...,...,...,...,...,...,...,...
68112,68112,958637,The Princess and the Bodyguard,6.500,8,90,en,Lexi is devastated when asked to give up her l...,7.413,"Romance, TV Movie","MOVIE_ID: 958637, Title: The Princess and the ..."
68113,68113,92950,Wife! Be Like a Rose!,6.813,8,74,ja,"Kimiko, a Tokyo white-collar working girl, liv...",1.544,Drama,"MOVIE_ID: 92950, Title: Wife! Be Like a Rose!,..."
68114,68114,55647,Red Peony Gambler: Biographies of a Gambling Room,5.900,8,110,ja,"Junko Fuji returns as Oryu the Red Peony, a wa...",2.611,"Action, Drama","MOVIE_ID: 55647, Title: Red Peony Gambler: Bio..."
68115,68115,172824,Loves Her Gun,5.600,8,99,en,Allie moves to Texas and embraces the slower p...,2.473,Drama,"MOVIE_ID: 172824, Title: Loves Her Gun, Overvi..."
68116,68116,340183,American Rescue Squad,10.000,8,90,en,A group of mysterious villains known as 'The A...,0.886,"Comedy, Action, Drama, Mystery, Fantasy","MOVIE_ID: 340183, Title: American Rescue Squad..."

In [2]:
movies['genres'].unique()

<StringArray>
[                       'Action, Science Fiction, Adventure',
                         'Adventure, Drama, Science Fiction',
                            'Drama, Action, Crime, Thriller',
               'Action, Adventure, Fantasy, Science Fiction',
                        'Science Fiction, Action, Adventure',
                                 'Action, Adventure, Comedy',
                        'Adventure, Action, Science Fiction',
                                                     'Drama',
                                           'Thriller, Crime',
                                    'Comedy, Drama, Romance',
 ...
 'War, Drama, History, Adventure, Comedy, Romance, Thriller',
                            'Thriller, Crime, Drama, Comedy',
                              'Action, Horror, War, Fantasy',
                                'Mystery, Action, Adventure',
                           'Thriller, Action, Crime, Comedy',
                  'Action, Drama, Romance, Mystery, Fantasy',
             'Family, Animation, Adventure, Romance, Comedy',
                           'Crime, Thriller, History, Drama',
                                  'Romance, Comedy, Mystery',
                   'Comedy, Action, Drama, Mystery, Fantasy']
Length: 5827, dtype: str

In [3]:
movies['genres'].value_counts().reset_index()

                                             genres  count
0                                             Drama   7772
1                                            Comedy   5591
2                                       Documentary   3881
3                                    Drama, Romance   1994
4                                            Horror   1844
...                                             ...    ...
5822       Action, Drama, Romance, Mystery, Fantasy      1
5823  Family, Animation, Adventure, Romance, Comedy      1
5824                Crime, Thriller, History, Drama      1
5825                       Romance, Comedy, Mystery      1
5826        Comedy, Action, Drama, Mystery, Fantasy      1

[5827 rows x 2 columns]

In [4]:
def map_genre_category(genres):
    if pd.isna(genres):
        return "Unknown"
    
    genres = [g.strip() for g in genres.split(",")]

    # Rule 1: Documentary override
    if "Documentary" in genres:
        return "Documentary"

    # Priority order
    priority = [
        "Action",
        "Comedy",
        "Drama",
        "Crime",
        "Romance",
        "Horror",
        "Thriller",
        "Science Fiction",
        "Adventure",
        "Mystery",
        "Fantasy",
        "Family",
        "Animation",
        "War",
        "Western",
    ]

    main = None
    sub = None

    for p in priority:
        if p in genres:
            if not main:
                main = p
            elif not sub:
                sub = p
                break

    if main and sub:
        return f"{main} {sub}"
    elif main:
        return main
    else:
        return genres[0]

In [5]:
movies["genre_category"] = movies["genres"].apply(map_genre_category)

In [6]:
movies

,Unnamed: 0,id,title,vote_average,vote_count,runtime,original_language,overview,popularity,genres,combined_text,genre_category
0,0,27205,Inception,8.364,34495,148,en,"Cobb, a skilled thief who commits corporate es...",83.952,"Action, Science Fiction, Adventure","MOVIE_ID: 27205, Title: Inception, Overview: C...",Action Science Fiction
1,1,157336,Interstellar,8.417,32571,169,en,The adventures of a group of explorers who mak...,140.241,"Adventure, Drama, Science Fiction","MOVIE_ID: 157336, Title: Interstellar, Overvie...",Drama Science Fiction
2,2,155,The Dark Knight,8.512,30619,152,en,Batman raises the stakes in his war on crime. ...,130.643,"Drama, Action, Crime, Thriller","MOVIE_ID: 155, Title: The Dark Knight, Overvie...",Action Drama
3,3,19995,Avatar,7.573,29815,162,en,"In the 22nd century, a paraplegic Marine is di...",79.932,"Action, Adventure, Fantasy, Science Fiction","MOVIE_ID: 19995, Title: Avatar, Overview: In t...",Action Science Fiction
4,4,24428,The Avengers,7.710,29166,143,en,When an unexpected enemy emerges and threatens...,98.082,"Science Fiction, Action, Adventure","MOVIE_ID: 24428, Title: The Avengers, Overview...",Action Science Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...
68112,68112,958637,The Princess and the Bodyguard,6.500,8,90,en,Lexi is devastated when asked to give up her l...,7.413,"Romance, TV Movie","MOVIE_ID: 958637, Title: The Princess and the ...",Romance
68113,68113,92950,Wife! Be Like a Rose!,6.813,8,74,ja,"Kimiko, a Tokyo white-collar working girl, liv...",1.544,Drama,"MOVIE_ID: 92950, Title: Wife! Be Like a Rose!,...",Drama
68114,68114,55647,Red Peony Gambler: Biographies of a Gambling Room,5.900,8,110,ja,"Junko Fuji returns as Oryu the Red Peony, a wa...",2.611,"Action, Drama","MOVIE_ID: 55647, Title: Red Peony Gambler: Bio...",Action Drama
68115,68115,172824,Loves Her Gun,5.600,8,99,en,Allie moves to Texas and embraces the slower p...,2.473,Drama,"MOVIE_ID: 172824, Title: Loves Her Gun, Overvi...",Drama
68116,68116,340183,American Rescue Squad,10.000,8,90,en,A group of mysterious villains known as 'The A...,0.886,"Comedy, Action, Drama, Mystery, Fantasy","MOVIE_ID: 340183, Title: American Rescue Squad...",Action Comedy

In [11]:
movies['genre_category'].value_counts().reset_index()

              genre_category  count
0                      Drama   9220
1                     Comedy   5959
2               Comedy Drama   5897
3                Documentary   5660
4              Drama Romance   4068
..                       ...    ...
116  Science Fiction Western      1
117           Family Western      1
118              Fantasy War      1
119                Crime War      1
120        Animation Western      1

[121 rows x 2 columns]

In [7]:
from transformers import pipeline

e:\movie-recommender\movie_recommender_env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [11]:
pipe = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

Loading weights: 100%|██████████| 515/515 [00:01<00:00, 473.46it/s, Materializing param=model.shared.weight]

In [8]:
sug_categories = ['Action Drama', 'Drama Romance']

In [9]:
seq  = movies.loc[movies['genre_category'] == 'Action Drama', 'overview'].reset_index(drop=True)[0]

In [12]:
pipe(seq, sug_categories)

{'sequence': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
 'labels': ['Action Drama', 'Drama Romance'],
 'scores': [0.6748768091201782, 0.3251231908798218]}

In [13]:
import numpy as np

In [14]:
max_index = np.argmax(pipe(seq, sug_categories)['scores'])
max_label = pipe(seq, sug_categories)['labels'][max_index]
max_label

'Action Drama'

In [15]:
def generate_predictions(seq, cat):
    pred = pipe(seq, cat)
    
    max_index = np.argmax(pred['scores'])
    max_label = pred['labels'][max_index]
    
    return max_label

In [16]:
from tqdm import tqdm

In [18]:
actual_cats = []
pred_cats = []

In [19]:
for i in tqdm(range(0, 300)):
    seq = movies.loc[movies['genre_category'] == 'Action Drama', 'overview'].reset_index(drop=True)[i]

    pred = generate_predictions(seq, sug_categories)

    pred_cats.append(pred)
    actual_cats.append('Action Drama')

100%|██████████| 300/300 [04:42<00:00,  1.06it/s]

In [20]:
for i in tqdm(range(0, 300)):
    seq = movies.loc[movies['genre_category'] == 'Drama Romance', 'overview'].reset_index(drop=True)[i]

    pred = generate_predictions(seq, sug_categories)

    pred_cats.append(pred)
    actual_cats.append('Drama Romance')

100%|██████████| 300/300 [04:30<00:00,  1.11it/s]

In [21]:
print(len(actual_cats))
print(len(pred_cats))

600
600

In [22]:
pred_df = pd.DataFrame({
    'actual_genre': actual_cats,
    'predicted_genre': pred_cats
})

In [ ]:
pred_df

      actual_genre predicted_genre
0     Action Drama               A
1     Action Drama               A
2     Action Drama               A
3     Action Drama               A
4     Action Drama               A
..             ...             ...
595  Drama Romance               A
596  Drama Romance               A
597  Drama Romance               A
598  Drama Romance               A
599  Drama Romance               A

[600 rows x 2 columns]

In [23]:
pred_df['correct_predictions'] = np.where(pred_df['actual_genre'] == pred_df['predicted_genre'], 1, 0)
pred_df['correct_predictions'].sum() / len(pred_df)

np.float64(0.7983333333333333)

In [24]:
genre_categories = movies['genre_category'].dropna().unique().tolist()
genre_categories

['Action Science Fiction',
 'Drama Science Fiction',
 'Action Drama',
 'Action Comedy',
 'Drama',
 'Crime Thriller',
 'Comedy Drama',
 'Adventure Fantasy',
 'Drama Crime',
 'Drama Romance',
 'Action Adventure',
 'Drama Thriller',
 'Science Fiction Adventure',
 'Action Thriller',
 'Comedy Adventure',
 'Comedy Science Fiction',
 'Family Animation',
 'Horror Fantasy',
 'Action Fantasy',
 'Science Fiction Family',
 'Comedy Family',
 'Drama Adventure',
 'Drama Family',
 'Horror Thriller',
 'Action Crime',
 'Comedy',
 'Comedy Fantasy',
 'Fantasy Family',
 'Romance Fantasy',
 'Drama War',
 'Thriller Mystery',
 'Drama Horror',
 'Horror Science Fiction',
 'Action Romance',
 'Action War',
 'Drama Mystery',
 'Comedy Horror',
 'Thriller War',
 'Comedy Crime',
 'Comedy Romance',
 'Romance Adventure',
 'Thriller Science Fiction',
 'Drama Fantasy',
 'Adventure Family',
 'Science Fiction',
 'Crime Horror',
 'Western',
 'Horror',
 'Action Horror',
 'Crime Adventure',
 'Horror Mystery',
 'Crime',
 'Romance Thriller',
 'Romance Family',
 'Adventure Mystery',
 'Drama Animation',
 'Romance Horror',
 'Action Mystery',
 'Drama Western',
 'Comedy Western',
 'Thriller',
 'Horror Adventure',
 'War',
 'Documentary',
 'Science Fiction Mystery',
 'Comedy Animation',
 'Thriller Animation',
 'Comedy War',
 'Action Western',
 'Comedy Thriller',
 'Comedy Mystery',
 'Action Animation',
 'Crime Romance',
 'Science Fiction Animation',
 'Action',
 'Romance',
 'Thriller Adventure',
 'Fantasy',
 'Adventure Western',
 'Romance Science Fiction',
 'Science Fiction Fantasy',
 'Mystery',
 'Adventure',
 'Animation',
 'Thriller Fantasy',
 'Family',
 'Fantasy Animation',
 'Action Family',
 'Music',
 'Adventure Animation',
 'Crime Science Fiction',
 'Mystery Fantasy',
 'Romance Animation',
 'TV Movie',
 'Crime Family',
 'War Western',
 'Romance Western',
 'Horror Western',
 'Adventure War',
 'Thriller Western',
 'Crime Mystery',
 'Mystery Animation',
 'Mystery Family',
 'Science Fiction War',
 'Fantasy Western',
 'Crime Western',
 'Romance War',
 'Horror Animation',
 'History',
 'Romance Mystery',
 'Mystery Western',
 'Thriller Family',
 'Crime Fantasy',
 'Animation War',
 'Science Fiction Western',
 'Family Western',
 'Horror War',
 'Fantasy War',
 'Crime War',
 'Animation Western',
 'Horror Family']

In [25]:
ids = []
pred_genres = []

missing_genres = movies.loc[movies['genre_category'].isna(), ['id','overview']].reset_index(drop=True)

In [26]:
for i in tqdm(range(0, len(missing_genres))):
    seq = missing_genres['overview']
    pred_genres.append([generate_predictions(seq, genre_categories)])
    ids.append([missing_genres['id'][i]])

0it [00:00, ?it/s]

In [27]:
movies.isnull().sum()

Unnamed: 0           0
id                   0
title                0
vote_average         0
vote_count           0
runtime              0
original_language    0
overview             0
popularity           0
genres               0
combined_text        0
genre_category       0
dtype: int64

In [ ]:
movies_sample = movies[['overview','genre_category']].dropna().sample(100, random_state=42).reset_index(drop=True)

In [32]:
def gen_prediction(seq, genres):

    pred = pipe(
        seq,
        genres,
        hypothesis_template="This movie is a {} film."
    )

    return pred['labels'][0]

In [33]:
actual_gens = []
pred_gens = []

for i in tqdm(range(len(movies_sample))):

    seq = movies_sample['overview'][i]
    actual = movies_sample['genre_category'][i]

    pred = gen_prediction(seq, genre_categories)

    actual_gens.append(actual)
    pred_gens.append(pred)

  1%|          | 6/500 [08:50<12:07:27, 88.36s/it]

KeyboardInterrupt:

In [ ]:
predict_df = pd.DataFrame({
    'actual_genre': actual_gens,
    'predicted_genre': pred_gens
})

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
accuracy = accuracy_score(predict_df['actual_genre'], predict_df['predicted_genre'])

print("Accuracy:", accuracy)

In [ ]:
print(classification_report(
    predict_df['actual_genre'],
    predict_df['predicted_genre']
))

In [34]:
movies

,Unnamed: 0,id,title,vote_average,vote_count,runtime,original_language,overview,popularity,genres,combined_text,genre_category
0,0,27205,Inception,8.364,34495,148,en,"Cobb, a skilled thief who commits corporate es...",83.952,"Action, Science Fiction, Adventure","MOVIE_ID: 27205, Title: Inception, Overview: C...",Action Science Fiction
1,1,157336,Interstellar,8.417,32571,169,en,The adventures of a group of explorers who mak...,140.241,"Adventure, Drama, Science Fiction","MOVIE_ID: 157336, Title: Interstellar, Overvie...",Drama Science Fiction
2,2,155,The Dark Knight,8.512,30619,152,en,Batman raises the stakes in his war on crime. ...,130.643,"Drama, Action, Crime, Thriller","MOVIE_ID: 155, Title: The Dark Knight, Overvie...",Action Drama
3,3,19995,Avatar,7.573,29815,162,en,"In the 22nd century, a paraplegic Marine is di...",79.932,"Action, Adventure, Fantasy, Science Fiction","MOVIE_ID: 19995, Title: Avatar, Overview: In t...",Action Science Fiction
4,4,24428,The Avengers,7.710,29166,143,en,When an unexpected enemy emerges and threatens...,98.082,"Science Fiction, Action, Adventure","MOVIE_ID: 24428, Title: The Avengers, Overview...",Action Science Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...
68112,68112,958637,The Princess and the Bodyguard,6.500,8,90,en,Lexi is devastated when asked to give up her l...,7.413,"Romance, TV Movie","MOVIE_ID: 958637, Title: The Princess and the ...",Romance
68113,68113,92950,Wife! Be Like a Rose!,6.813,8,74,ja,"Kimiko, a Tokyo white-collar working girl, liv...",1.544,Drama,"MOVIE_ID: 92950, Title: Wife! Be Like a Rose!,...",Drama
68114,68114,55647,Red Peony Gambler: Biographies of a Gambling Room,5.900,8,110,ja,"Junko Fuji returns as Oryu the Red Peony, a wa...",2.611,"Action, Drama","MOVIE_ID: 55647, Title: Red Peony Gambler: Bio...",Action Drama
68115,68115,172824,Loves Her Gun,5.600,8,99,en,Allie moves to Texas and embraces the slower p...,2.473,Drama,"MOVIE_ID: 172824, Title: Loves Her Gun, Overvi...",Drama
68116,68116,340183,American Rescue Squad,10.000,8,90,en,A group of mysterious villains known as 'The A...,0.886,"Comedy, Action, Drama, Mystery, Fantasy","MOVIE_ID: 340183, Title: American Rescue Squad...",Action Comedy

In [36]:
movies.to_csv('data\movies_with_genres.csv', index=False)

<>:1: SyntaxWarning: invalid escape sequence '\m'
<>:1: SyntaxWarning: invalid escape sequence '\m'
C:\Users\jeeva\AppData\Local\Temp\ipykernel_20332\4019283069.py:1: SyntaxWarning: invalid escape sequence '\m'
  movies.to_csv('data\movies_with_genres.csv', index=False)